INSERT INTO shadee_dev.product (name, description, image, price) VALUES
('Fenty Beauty Pro Filt\'r Soft Matte Longwear Foundation', 'Fond de teint liquide mat longue tenue, couvrance moyenne à totale, pour un fini peau nette sans brillance.', 'images/fenty-pro-filtr-soft-matte-longwear-foundation.jpg', 39.90),
('Fenty Beauty Pro Filt\'r Hydrating Longwear Foundation', 'Fond de teint hydratant et confortable, couvrance modulable, idéal peaux normales à sèches.', 'images/fenty-pro-filtr-hydrating-longwear-foundation.jpg', 38.00),
('Fenty Beauty Pro Filt\'r Soft Matte Powder Foundation', 'Fond de teint poudre mat, tenue longue durée et effet peau lisse, pratique pour retouches.', 'images/fenty-pro-filtr-soft-matte-powder-foundation.jpg', 34.00),
('Fenty Beauty Eaze Drop Blurring Skin Tint', 'Skin-tint fluide effet seconde peau, unifie légèrement le teint pour un rendu naturel.', 'images/fenty-eaze-drop-blurring-skin-tint.jpg', 36.00),
('Fenty Beauty Pro Filt\'r Instant Retouch Concealer', 'Anti-cernes et correcteur haute couvrance, corrige cernes et imperfections avec un fini naturel.', 'images/fenty-pro-filtr-instant-retouch-concealer.jpg', 29.90),
('Charlotte Tilbury Airbrush Flawless Foundation', 'Fond de teint liquide couvrant et lumineux, unifie le teint pour un fini peau parfaite.', 'images/charlotte-tilbury-airbrush-flawless-foundation.jpg', 52.00),
('Charlotte Tilbury Light Wonder Foundation', 'Fond de teint léger effet “peau nue”, texture fluide pour un teint frais et naturel.', 'images/charlotte-tilbury-light-wonder-foundation.jpg', 52.00),
('Charlotte Tilbury Magic Away Concealer', 'Anti-cernes crémeux et lumineux, corrige cernes et taches pour un regard reposé.', 'images/charlotte-tilbury-magic-away-concealer.jpg', 35.00),
('NARS Sheer Glow Foundation', 'Fond de teint liquide radiant qui unifie le teint et donne de l’éclat sans effet masque.', 'images/nars-sheer-glow-foundation.jpg', 44.95),
('NARS Natural Radiant Longwear Foundation', 'Fond de teint longue tenue, couvrance modulable et fini naturel lumineux pour toutes peaux.', 'images/nars-natural-radiant-longwear-foundation.jpg', 46.00),
('NARS Velvet Matte Skin Tint', 'Skin tint mat léger, unifie subtilement le teint pour un fini naturel et durable.', 'images/nars-velvet-matte-skin-tint.jpg', 40.00),
('NARS Radiant Creamy Concealer', 'Correcteur/anticernes crémeux et lumineux, camoufle cernes et irrégularités pour un regard frais.', 'images/nars-radiant-creamy-concealer.jpg', 39.00),
('NARS Soft Matte Complete Concealer', 'Correcteur mat mais crémeux, camouflage naturel des cernes et rougeurs, fini velouté.', 'images/nars-soft-matte-complete-concealer.jpg', 38.00),
('Kevyn Aucoin The Sensual Skin Enhancer', 'Fond de teint / correcteur très couvrant, idéal pour camoufler imperfections ou uniformiser le teint.', 'images/kevyn-aucoin-sensual-skin-enhancer.jpg', 32.00),
('Kevyn Aucoin The Etherealist Super Natural Concealer', 'Correcteur fluide haute définition, fini naturel et invisible pour cernes et irrégularités.', 'images/kevyn-aucoin-etherealist-super-natural-concealer.jpg', 29.95),
('Kevyn Aucoin SSE Ultra-Correction Stick', 'Correcteur stick haute couvrance, pratique pour retouches et couvrir localement imperfections.', 'images/kevyn-aucoin-sse-ultra-correction-stick.jpg', 31.50),
('Maybelline Fit Me Matte + Poreless Foundation', 'Fond de teint fluide matifiant, affine les pores et contrôle la brillance, idéal peaux mixtes à grasses.', 'images/maybelline-fit-me-matte-poreless-foundation.jpg', 9.95),
('Maybelline Fit Me Dewy + Smooth Foundation', 'Fond de teint fluide pour un rendu glowy et naturel, bonne tenue pour peaux normales à sèches.', 'images/maybelline-fit-me-dewy-smooth-foundation.jpg', 10.95),
('Maybelline SuperStay Full Coverage Foundation', 'Fond de teint couvrance totale, tenue longue durée, idéal pour un maquillage uniforme toute la journée.', 'images/maybelline-superstay-full-coverage-foundation.jpg', 11.99),
('Maybelline Instant Age Rewind Concealer', 'Anti-cernes fluide avec applicateur éponge, couvre cernes, poches et imperfections.', 'images/maybelline-instant-age-rewind-concealer.jpg', 10.99),
('Maybelline Fit Me Concealer', 'Correcteur fluide, couvre cernes et petites imperfections avec un fini naturel.', 'images/maybelline-fit-me-concealer.jpg', 9.99),
('Maybelline Instant Age Rewind Brightener', 'Correcteur/illuminateur pour le contour des yeux, pour un regard lumineux et reposé.', 'images/maybelline-instant-age-rewind-brightener.jpg', 11.50),
('Maybelline SuperStay Concealer', 'Correcteur haute couvrance, longue tenue, idéal pour masquer imperfections et uniformiser le teint.', 'images/maybelline-superstay-concealer.jpg', 12.99),
('L’Oréal Paris True Match Foundation', 'Fond de teint liquide modulable, fini naturel, très large choix de teintes, pour tous types de peau.', 'images/loreal-true-match-foundation.jpg', 14.99),
('L’Oréal Paris Infallible 24H Fresh Wear Foundation', 'Fond de teint longue tenue, couvrance modulable et confortable, tenue 24 h, pour un teint unifié tout au long de la journée.', 'images/loreal-infallible-24h-fresh-wear-foundation.jpg', 15.99),
('L’Oréal Paris Infallible Matte Cover Foundation', 'Fond de teint matifiant longue tenue, contrôle la brillance, idéal peaux mixtes à grasses.', 'images/loreal-infallible-matte-cover-foundation.jpg', 15.99),
('L’Oréal Paris Infallible 24H Fresh Wear Foundation Concealer', 'Correcteur fluide longue tenue, couvre imperfections et cernes pour un teint homogène.', 'images/loreal-infallible-fresh-wear-concealer.jpg', 14.99),
('MAC Studio Fix Fluid Foundation', 'Fond de teint liquide culte, couvrance modulable et tenue longue durée, fini naturel matifié.', 'images/mac-studio-fix-fluid-foundation.jpg', 38.00),
('MAC Pro Longwear Concealer', 'Correcteur longue tenue haute couvrance, idéal pour cernes et imperfections persistantes.', 'images/mac-pro-longwear-concealer.jpg', 38.00);


INSERT INTO shadee_dev.product_undertone (product_id, undertone_id) VALUES
(1, 1), (1, 3),  
(2, 2), (2, 3),  
(3, 1),          
(4, 2),          
(5, 3),          
(6, 1),          
(7, 2),         
(8, 1),         
(9, 2),        
(10, 1),         
(11, 3),         
(13, 3),         
(14, 1), (14, 2),
(15, 3);         

INSERT INTO shadee_dev.product_skin_type (product_id, skin_type_id) VALUES
(1, 1), (1, 2), (1, 3), (1, 4),  
(2, 2), (2, 3),                  
(3, 1), (3, 4),                  
(4, 2), (4, 3),                  
(5, 1), (5, 2), (5, 3), (5, 4),  
(6, 1), (6, 4),                  
(7, 2), (7, 3),                 
(8, 1), (8, 4),                 
(9, 2), (9, 3),                 
(10, 1), (10, 4),                
(11, 2), (11, 3),                
(12, 1), (12, 2), (12, 3), (12, 4), 
(13, 1), (13, 2), (13, 3), (13, 4), 
(14, 1), (14, 4),                
(15, 2), (15, 3);               

INSERT INTO shadee_dev.product_skin_color (product_id, skin_color_id) VALUES
(1, 1), (1, 2), 
(2, 1), (2, 2),  
(3, 1),          
(4, 2),          
(5, 1), (5, 2),  
(6, 1), (6, 2),  
(7, 1), (7, 2),  
(8, 1), (8, 2),  
(9, 1), (9, 2),  
(10, 1), (10, 2),
(11, 1), (11, 2),
(12, 1), (12, 2),
(13, 1), (13, 2),
(14, 1), (14, 2),
(15, 1), (15, 2);

